version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: ihearyou_postgres
    env_file: .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ihearyou_network

  admin:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ihearyou_admin
    env_file: .env
    environment:
      POSTGRES_CONN_STRING: ${POSTGRES_CONN_STRING}
      BOT_TOKEN: ${BOT_TOKEN}
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    command: ["poetry", "run", "uvicorn", "data.admin_panel:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    networks:
      - ihearyou_network
    restart: unless-stopped

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ihearyou_bot
    env_file: .env
    environment:
      POSTGRES_CONN_STRING: ${POSTGRES_CONN_STRING}
      BOT_TOKEN: ${BOT_TOKEN}
      ADMINS: ${ADMINS}
    depends_on:
      postgres:
        condition: service_healthy
    command: ["poetry", "run", "python", "aiogram_run.py"]
    networks:
      - ihearyou_network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  ihearyou_network:
    driver: bridge