# Base file for multiple compose files.
# for dev: "compose up" will auto-use compose.override.yml also
# for production: "docker compose -f compose.yml -f compose.prod.yml up"
# i.e. ignore compose.override.yml in production.

services:
  db:
    image: postgres:16.3-alpine3.19
    restart: unless-stopped
    env_file: ../.env
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - ${DB_PORT:-5432}:5432
volumes:
  pg_data:
